In [59]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [60]:
X, y = make_regression(n_samples = 10000)
print(X.shape, y.shape)


(10000, 100) (10000,)


In [61]:
X

array([[-0.93473413, -0.04137874, -1.47435606, ..., -1.01026224,
         1.15514148,  1.16792141],
       [-0.59830423, -2.4281984 , -0.04540794, ..., -0.85985086,
        -0.72700965,  1.20094271],
       [ 0.21159383, -1.10803502, -1.04988622, ..., -0.81271778,
         0.80994773, -2.73416328],
       ...,
       [-0.44785221, -0.29744062,  0.51196471, ..., -0.46095611,
        -1.26694996, -0.23586   ],
       [-0.59900057,  0.04583117,  0.78449663, ..., -0.36648339,
         1.75676239, -0.38711696],
       [ 1.16455952,  0.06786122,  0.65297705, ..., -0.21345905,
         0.83828827, -0.4185727 ]])

In [62]:
reg = LinearRegression().fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_

7.758068010650475e-26


array([ 4.25840173e-14,  4.61852778e-14,  1.77635684e-15, -5.86197757e-14,
       -7.10542736e-15, -2.28705943e-14,  1.77635684e-14,  1.28785871e-14,
       -6.57252031e-14, -1.42108547e-14,  4.79616347e-14, -1.77635684e-15,
        1.86517468e-14, -3.33066907e-15,  1.06581410e-14, -4.44089210e-14,
        2.07611706e-14, -3.08642001e-14,  3.65089737e+01,  3.37507799e-14,
        2.60902411e-14,  0.00000000e+00, -2.13162821e-14,  3.19744231e-14,
        1.95399252e-14, -2.13162821e-14,  7.10542736e-15, -5.32907052e-15,
        9.76996262e-15,  1.77635684e-15, -6.03961325e-14, -1.06581410e-14,
       -5.41788836e-14, -1.15463195e-14, -8.88178420e-15,  1.19904087e-14,
        2.08721929e-14, -1.33226763e-14,  3.73034936e-14,  2.66453526e-15,
       -7.10542736e-15,  1.24344979e-14,  5.32907052e-15, -2.75335310e-14,
       -1.95399252e-14,  8.88178420e-15,  3.19744231e-14,  1.77635684e-14,
        2.36330980e+01, -3.10862447e-15,  5.32907052e-15, -2.75335310e-14,
        1.06581410e-14, -

Мы получили с помощью sklearn значение MSE << 1 (близкий к 0), это неудивительно, т.к. у нас изначально линейная зависимость



In [63]:
from sklearn.linear_model import SGDRegressor
reg = SGDRegressor(alpha=0.00000001).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_


2.0478358164277794e-12


array([-2.04010159e-08,  2.27050077e-08, -2.17205071e-08,  4.79493381e-08,
        9.38322952e-09, -2.99277742e-09,  3.73223636e-08, -4.01632361e-08,
        1.25519604e-08,  1.99867164e-08, -4.37350807e-08,  2.50242808e-08,
        8.75815711e-09,  1.35709388e-08, -2.36588872e-09,  2.56878396e-08,
       -2.79345696e-09, -3.68169326e-08,  3.65089734e+01, -1.21803831e-08,
        9.92898963e-09,  2.96999677e-08,  4.06115955e-08, -1.27918597e-09,
       -9.32883201e-09,  7.07705239e-09, -2.76722648e-08,  2.02628303e-08,
       -1.19631523e-08, -1.75753699e-08, -4.22915618e-08,  3.67332937e-08,
        1.13271905e-08, -1.67589929e-08, -2.87343536e-09, -4.77571739e-08,
        1.17586927e-08, -3.88413715e-08,  4.92902895e-08,  2.48825780e-08,
        3.27385349e-08, -1.32657147e-08, -7.58857019e-09,  5.38980011e-09,
       -1.77972366e-08, -2.23509020e-08, -2.64713954e-10,  4.06553833e-08,
        2.36330977e+01, -1.86919910e-09,  2.78128923e-08,  2.12691890e-08,
       -3.86420211e-08, -

У нас ошибка тоже близка к нулю, но порядок отличается очень сильно (10^(-12) и 10^(-25)) - это разницу можно объяснить тем, что мы ввели "штраф" в виде регуляризации с $\alpha$ = 0.00000001. Но на самом деле нам незачем вводить лишний вес, потому регуляризацию делают, чтобы избежать переобучения, влияния шумов или решить не совсем корректную задачу (и т.д. и т.п.). У нас таких проблем нет, ничего добавлять к функции к ошибок не надо, возьмем   $\alpha$ = 0.

In [64]:
reg = SGDRegressor(alpha=0).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_

5.017489041293499e-25


array([-2.17579840e-14,  1.85106094e-14,  3.24078131e-15, -5.37801812e-16,
        7.46085802e-15,  1.52174050e-14, -2.06975760e-15, -1.75859611e-14,
        3.49932467e-14,  1.52709257e-14,  8.55326062e-15,  1.22607823e-14,
       -1.68901087e-16, -4.42119757e-15, -5.67514253e-15,  3.29852517e-14,
        1.75222275e-14, -4.81160398e-15,  3.65089737e+01, -1.56763783e-14,
        1.24788301e-15,  1.43833787e-14,  2.06579209e-14,  9.46165811e-15,
       -5.12311808e-16,  6.54370180e-15, -1.99777161e-15, -3.74887617e-14,
        4.79852841e-15,  1.40508105e-14, -2.36985051e-14,  5.13134565e-15,
        1.41452980e-14,  2.57679079e-15,  1.89871702e-15, -7.27550288e-15,
       -3.95137355e-15, -3.04419009e-15,  3.21069268e-15,  1.44550976e-14,
        2.01152766e-14,  1.84300351e-14, -1.69083318e-14, -2.22490713e-15,
        1.24597944e-14,  9.41992289e-15, -5.70082002e-15, -1.28082468e-16,
        2.36330980e+01,  5.19538647e-15,  8.71231632e-15,  2.37236831e-14,
       -1.83970996e-14, -

Теперь различие только в 5 раз, а не на порядок. Эта разница уже может объясняться тем, что "под капотом" sklearn алгоритм реализован лучше, чем у нас

Алиев - 5 букв $=>$ у меня 2 вариант (если я верно умею считать) 

In [65]:
import random

def sgn(w):
  return np.array([np.sign(w[i]) for i in range(w.shape[0])])


class LinearRegression(object):
    def __init__(self, alpha=0.0001, l_ratio=0.01, tol=0.00001, max_iter=1000):
      self.alpha = alpha
      self.l_ratio = l_ratio
      self.tol = tol
      self.max_iter = max_iter
      self.w = None
   
    def fit(self, X, y):
      n = X.shape[1]
      v = np.array([10**20 for _ in range(X.shape[1])])
      w = np.array([random.random() for _ in range(X.shape[1])])
      iter = 0
      while (abs(mean_squared_error(X.dot(w), y) - mean_squared_error(X.dot(v),y)) > self.tol and iter <= self.max_iter):
        grad = 2/n*(X.T.dot(X.dot(w) - y))
        w, v = w - grad * self.alpha, w
        iter += 1
      #print(iter)
      self.w = w

    def coef_(self):
      return self.w
    
    def predict(self, X):
        return np.dot(self.w, X.T)

    def MSE(self, X, y):
      return mean_squared_error(self.predict(X), y)

my_reg = LinearRegression()
my_reg.fit(X, y)
my_reg.coef_()

print(mean_squared_error(y, my_reg.predict(X)))

assert mean_squared_error(y, my_reg.predict(X)) < 1e-3
print('You are amazing! Great work!')

0.0002662093652053855
You are amazing! Great work!


tol пришлось уменьшать (по сравнению с тем, что было изначально). Вообще метод уменьшения разницы MSE не всегда хороший. Теперь добавим l1-регуляризацию (вообще я понял, что можно было делать одну ячейку с классом сразу с регуляризацией, просто в обычном случае подавать 0, но уже поздно что-то менять)

In [66]:
def sgn(w):
  return np.array([np.sign(w[i]) for i in range(w.shape[0])])


class LinearRegression(object):
    def __init__(self, alpha=0.0001, l_ratio=0.01, tol=0.00001, max_iter=1000):
      self.alpha = alpha
      self.l_ratio = l_ratio
      self.tol = tol
      self.max_iter = max_iter
      self.w = None
   
    def fit(self, X, y):
      n = X.shape[1]
      v = np.array([10**20 for _ in range(X.shape[1])])
      w = np.array([random.random() for _ in range(X.shape[1])])
      iter = 0
      while (abs(mean_squared_error(X.dot(w), y) - mean_squared_error(X.dot(v),y)) > self.tol and iter <= self.max_iter):
        grad = 2/n*(X.T.dot(X.dot(w) - y)) + self.l_ratio*sgn(w)
        w, v = w - grad * self.alpha, w
        iter += 1
      #print(iter)
      self.w = w

    def coef_(self):
      return self.w
    
    def predict(self, X):
        return np.dot(self.w, X.T)

    def MSE(self, X, y):
      return mean_squared_error(self.predict(X), y)

my_reg = LinearRegression()
my_reg.fit(X, y)


print(mean_squared_error(y, my_reg.predict(X)))

assert mean_squared_error(y, my_reg.predict(X)) < 1e-3
print('You are amazing! Great work!')


0.0002693485400203715
You are amazing! Great work!


Вобще с регуляризацией вышло чуть хуже, причины те же

In [67]:
from sklearn.linear_model import Lasso
regr = Lasso(alpha = 0.01).fit(X, y)
print(mean_squared_error(y, regr.predict(X)))


0.0009942742167419684


Вообще немного странно, что MSE стал больше, чем у нас, но возможно дело в том, что внутри l1 реализован хорошо (и там другие критерии остановки), отсюда регуляризация проявляется сильнее

[ 1  1 -1]
